title: "unicorn의 취향"
description: "관심사, 기록, 그리고 소소한 취향에 관한 공간입니다."
theme: jekyll-theme-cayman

# 파비콘 설정
favicon: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f984.png"

future: true
